### PR TITLE
Laravel 9.x Shift

### PR DESCRIPTION
**Pull request by simonostendorf**
This pull request includes the changes for upgrading to Laravel 9.x. Feel free to commit any additional changes to the `shift-129283` branch.

**Before merging**, you need to:

- Checkout the `shift-129283` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, try with `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts).

### CODE REVIEW

**Comment by simonostendorf** [comment]
:information_source: Laravel 9 moved the `resources/lang` folder to the top level of the project. While Shift [automated this change](https://github.com/fsr5-fhaachen/strichlistensystem/pull/96/commits/261fb1e0384108acf7d17e77abc9e36e7d17247c?w=1), you may have additional references to the previous folder which need to be updated.

**Comment by simonostendorf** [comment]
:warning: Laravel 9 upgraded to Flysystem 3.0 causing the behavior of the `Storage` facade to change slightly:

* Write operations (such as `put` and `write`) now overwrite existing files by default and return `false` instead of throwing an exception.
* Read operations (such as `get` and `download`) now return `null` instead of a `FileNotFoundException` when a file is missing.
* The `delete` operation now returns `true` even if the file did not exist.

For more details, you may review the [Flysystem 3.x](https://laravel.com/docs/9.x/upgrade#flysystem-3) section of the _Upgrade Guide_.

**Comment by simonostendorf** [comment]
:warning: The `FILESYSTEM_DRIVER` environment variable was renamed to `FILESYSTEM_DISK` in Laravel 9. Shift attempted to [automate this change](https://github.com/fsr5-fhaachen/strichlistensystem/pull/96/commits/66de80690714816e3db6cb8eadb3e2115366bd3c?w=1), but you should review any additional environment configuration and rename this variable.

**Comment by simonostendorf** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/fsr5-fhaachen/strichlistensystem/pull/96/commits/71c367dc786a8629b996e81e06472978ffd2efb4?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert 71c367dc` and make the [config file changes](https://github.com/laravel-shift/laravel-8.x/pull/5/commits/2d69ee7809de36503133641b12f0f3ba299b063a) manually.

**Comment by simonostendorf** [comment]
:information_source: The `FILESYSTEM_CLOUD` environment variable was removed in a later release of Laravel 8. While you may still use the `cloud` disk, you are encouraged to [configure your own disks](https://laravel.com/docs/9.x/filesystem#configuration).

**Comment by simonostendorf** [comment]
:warning: The `token` driver for API authentication is no longer available. This driver was not very robust and was removed from the documentation. Laravel now recommends using [Sanctum](https://laravel.com/docs/9.x/sanctum).

If you were using the `token` driver, you may re-add it within your `auth.php` configuration file then migrate to _Sanctum_ at your convenience.

**Comment by simonostendorf** [comment]
:information_source: Shift [updated your dependencies](https://github.com/fsr5-fhaachen/strichlistensystem/pull/96/commits/80579e9853f0fbbe3329693a3f35f557cb30bc4c?w=1) for Laravel 9. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 9. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

**Comment by simonostendorf** [comment]
:information_source: Laravel 9 adopted [anonymous migrations](https://laravel-news.com/laravel-anonymous-migrations). Shift [automated this change](https://github.com/fsr5-fhaachen/strichlistensystem/pull/96/commits/51fa7b781c81e3f95d32212fe931057852aec934?w=1) to align with modern Laravel conventions and avoid naming migrations.

**Comment by simonostendorf** [comment]
:information_source: Sanctum 3.x added an `expires_at` column to support expiring tokens. Shift detected you have a migration for this table and [created a migration](https://github.com/fsr5-fhaachen/strichlistensystem/pull/96/commits/577623ab00dbec3709b7c917b57973e1554747c9?w=1) for this new column. Be sure to run `php artisan migrate` to complete your upgrade.

**Comment by simonostendorf** [comment]
:warning: Shift detected you are running Laravel Sail. If you have not customized your stack, you may run `php artisan sail:install` to regenerate the latest `docker-compose.yml`. Otherwise, you should ensure your stack is running PHP 8.0 or higher.

**Comment by simonostendorf** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6. If you are directly interacting with any Symfony component, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.0/UPGRADE-6.0.md) for additional changes.

**Comment by simonostendorf** [comment]
:information_source: Laravel 9 now uses Vite to build frontend assets. While you may continue to use Laravel Mix, it is no longer the default. If you wish to modernize your application to use Vite, you may run the [Vite Converter](https://laravelshift.com/convert-laravel-mix-to-vite) for free.

**Comment by simonostendorf** [comment]
:warning: Laravel 9.x has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes or security updates. Shift recommends continuing to upgrade to the latest version (Laravel 11.x).

**Comment by simonostendorf** [comment]
also do npm dependency update

**Review by jpih — APPROVED** [review]

**Pull request merged**
