### PR TITLE
Laravel 10.x Shift

### PR DESCRIPTION
**Pull request by simonostendorf**
This pull request includes the changes for upgrading to Laravel 10.x. Feel free to commit any additional changes to the `shift-130321` branch.

**Before merging**, you need to:

- Checkout the `shift-130321` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, try with `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts).

### CODE REVIEW

**Comment by simonostendorf** [comment]
:information_source: Starting with Laravel 10, the `lang` folder is no longer included in a default Laravel application. Laravel now recursively merges any customizations with framework defaults.

Shift [streamlined your language files](https://github.com/fsr5-fhaachen/strichlistensystem/pull/119/commits/274a5a121d0ce55caf554b44c9ca3f7a43f4063f?w=1) by removing them since they did not contain any customizations. If you wish to keep the full set of language, Shift recommends running `artisan config:publish --all --force` to get the latest configuration files from Laravel 11, then reapplying the customizations Shift streamlined.

**Comment by simonostendorf** [comment]
:information_source: Laravel 10 now verifies hashed values were created by the same hashing algorithm. If your application has hashed values created by different hashing algorithms, you may set the `verify` option to `false` in your hashing configuration. For more details, you may review the [original PR](https://github.com/laravel/laravel/pull/6258).

**Comment by simonostendorf** [comment]
:information_source: Shift [updated your dependencies](https://github.com/fsr5-fhaachen/strichlistensystem/pull/119/commits/f8ef0ed9122f68761274fd00809bbaded0f1e845?w=1) for Laravel 10. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 10. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

**Comment by simonostendorf** [comment]
:warning: Shift detected you are running Laravel Sail. If you have not customized your stack, you should run `php artisan sail:install` to regenerate the latest `docker-compose.yml`. Otherwise, Shift attempted to update Sail for PHP 8.1. However, you should review your `docker-compose.yml` to ensure your stack is running PHP 8.1 or higher.

**Comment by simonostendorf** [comment]
:information_source: Laravel renamed the `password_resets` table to `password_reset_tokens`. While an optional change, Shift detected you have a migration for the original table and [created a migration](https://github.com/fsr5-fhaachen/strichlistensystem/pull/119/commits/9cdb9bb2da77cfc679a2dd4d496efea311a40fc4?w=1) to rename the table. You should check for any additional references to the `password_resets` table and run `php artisan migrate` to complete your upgrade.

**Comment by simonostendorf** [comment]
:information_source: Laravel 10 added PHP type hints to all user-land code included in a new Laravel application. In an effort to modernize your code, Shift [added type hints](https://github.com/fsr5-fhaachen/strichlistensystem/pull/119/commits/3d72df60d9462f27926bd533a588d038c62a5bbe?w=1) to any method which is used by Laravel.

**Comment by simonostendorf** [comment]
:information_source: Now with type hints in your code, defining types within PHP DocBlocks is redundant. Laravel has removed all of the `@param` and `@return` tags from its DocBlocks where types are defined with PHP. Similarly, Shift [removed these tags](https://github.com/fsr5-fhaachen/strichlistensystem/pull/119/commits/7ecc349821425bc93b62638a0437c4318eefbaf5?w=1) from any DocBlock where the code now has _equivalent_ type hints.

**Comment by simonostendorf** [comment]
:information_source: Shift understands developers have different preferences when it comes to type hints. All of Shift's automation is done in nice, atomic commits. This makes it easier to undo any of the changes Shift makes.

If you wish to undo the changes relating to type hints, you may run:

- `git revert 7ecc349` to revert the DocBlock changes.
- `git revert bc76d84` to revert the type hints added from DocBlocks.
- `git revert 3d72df6` to revert the type hints added for Laravel 10.

**Comment by simonostendorf** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6.2. Shift detected references to Symfony classes within your application. These are most likely type hints and can safely be ignored. If you are using Symfony classes directly or experience issues relating to Symfony, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.2/UPGRADE-6.2.md) for any additional changes.

**Comment by simonostendorf** [comment]
:warning: Laravel 10 requires Composer 2.2 or higher. You should verify the Composer version in your environments by running `composer --version` to ensure it meets this new requirement. If necessary, run `composer self-update` to update Composer.

**Comment by simonostendorf** [comment]
:warning: Laravel 10 requires PHP 8.1 or higher. You should verify the PHP version in your environments to ensure it meets this new requirement.

**Comment by simonostendorf** [comment]
:warning: Laravel 10. has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes . Shift recommends continuing to upgrade to the latest version (Laravel 11.x).

**Comment by simonostendorf** [comment]
:x: PHP syntax errors were detected after running your Shift. Often these are simply differences between the PHP version on the Shift server (8.2) and your project. Occasionally they are misplaced lines or duplicate import statements.

You may quickly check the PHP syntax locally by running `php -l` on the following files:

- [ ] app/Http/Controllers/PersonController.php

**Comment by jpih** [comment]
> ❌ PHP syntax errors were detected after running your Shift. Often these are simply differences between the PHP version on the Shift server (8.2) and your project. Occasionally they are misplaced lines or duplicate import statements.
> 
> You may quickly check the PHP syntax locally by running `php -l` on the following files:
> 
> * [ ]  app/Http/Controllers/PersonController.php

Fixed. Happened duo to automatically added (by Shift) type hint

**Pull request merged**
